cookie:
  expiry_days: 30
  key: some_random_secret_key # Change this to a random string
  name: some_cookie_name
credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Admin User
      password: "PASTE_FIRST_HASH_HERE"
    sales1:
      email: sales1@example.com
      name: Sales Person 1
      password: "PASTE_SECOND_HASH_HERE"
