cookie:
  expiry_days: 30
  key: random_signature_key
  name: some_cookie_name
credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Admin User
      password: $2b$12$R.S.M.PasswordHashHere
    sales1:
      email: sales1@example.com
      name: Sales Person 1
      password: $2b$12$R.S.M.PasswordHashHere
